### PR TITLE
bootstrap: add version for prow

### PR DESCRIPTION
**Pull request by ray-harris**

### CODE REVIEW

**Comment by arewm** [comment]
Is this only removing the authentication? How do you handle the possibility that the curl fails to return something useful?

**Comment by arewm** [comment]
Would it be better to "teach" PROW how to pull the build-harness itself (using its own credentials/hook into our org) so that the curl will not fail as much?

**Comment by ray-harris** [comment]
Prow doesn't have GitHub credentials unless you tag the repo as "private" but that then breaks the testing of our repos for reasons I've discussed in Slack.

**Comment by arewm** [comment]
Well that seems silly... 🙃 

Is it possible to vendorize the build harness _within_ PROW somehow? I do not have an issue with this PR, I am just trying to see if there is a way that we can bypass the rate limiting issues that we will likely be hitting.

**Comment by ray-harris** [comment]
You'd have to:
- vendorize the build harness in the `multicloud-operators-channel`, or
- update the openshift-ci-operator and ci-tools to allow the github creds to be provided without making the test results limited to only a few people

**Comment by arewm** [comment]
I approve of this to unblock, but I think we might need to figure out how to teach PROW to use this as a first class citizen of its implementation... whatever that entails.

**Pull request merged**
