### PR TITLE
Add the ability to manage ClusterClaims as Secrets

### PR DESCRIPTION
**Pull request by gurnben**
## Summary of Changes

This PR adds the ability to store and manage ClusterClaim-ed clusters as secrets in a host OCP cluster and starts to expose some of the framework we'll need to add support for different clusters-as-secrets targets in the future. 

Specifically, we expose five new functions:
* `bootstrap-ks/get-cluster-metadata` - A generic target that will extract all possible metadata from all sources, which can be extended in the future to conditionally extract other source information based on target platform, or attempt to extract data more flexibly.
* `bootstrap-ks/delete-cluster` - A generic target to delete clusters on any source which can be added to for any new target provided
* `bootstrap-ks/clusterclaim-save-secret` - save a clusterclaim's info as a single, readable secret from input information
* `bootstrap-ks/clusterclaim-save-secret-from-claim` - given a claim name, automatically extract all information from a clusterclaim and create a secret
* `bootstrap-ks/clusterclaim-delete-cluster` - delete a clusterclaim given its secret name

We also expose some specific targets for the ClusterClaim cluster/secret type which may be reusable for other OpenShift-type clusters as well as some specific targets to create/delete secrets and ClusterClaims

Regarding clusterclaims: We make one assumption - the same cluster is used to host the ClusterClaim and the secrets (we don't do multi-auth or delete).

### CODE REVIEW

**Comment by schmidtd** [comment]
Looks decent - do you end up with an assertion of sorts that you at least have user+pass or token?  Is that passed through to be asserted in oc/login?

**Comment by gurnben** [comment]
We wound up passing it on to the oc/login module - it was more work and added code than it was worth to do a multi-conditional-assert - especially because we don't do it in other BHE modules.  

`oc/login` provides a robust-enough error message to satisfy my concerns!

**Review by schmidtd — COMMENTED** [review]
/shrug

**Review by schmidtd — APPROVED** [review]
Let's give it a whirl...
/lgtm

**Pull request merged**
